### ISSUE TITLE
Change Host structure

### ISSUE THREAD

**Issue by msimonin** [BeyondTheClouds/enos#100]
In Enos we rely on execo.Host. 
It's desirable to change it into an home made structure since : 

* it's gplv3 code
* it's not very flexible in what we would like to express with Enos (e.g host accessibe through a proxycommand)

This will have some side effects on every provider and the extra.to_ansible_group function

**Comment by rcherrueau** [comment]
Good initiative.

I wanna add that, the first argument, about gplv3, is not a good argument :gnus:
