### ISSUE TITLE
admin-openrc file should reuse kolla values

### ISSUE THREAD

**Issue by rcherrueau** [BeyondTheClouds/enos#116]
Values `OS_AUTH_URL` and `OS_REGION_NAME` in the template [`admin-openrc.j2`](https://github.com/BeyondTheClouds/enos/blob/4e93e758bec6d412650fc0d88d54c62922f1555c/enos/templates/admin-openrc.jinja2) potentially are false values. The template should reuse variables `openstack_region_name` and `keystone_admin_url` provided by kolla-ansbile.

**Comment by msimonin** [comment]
I should add that our workflow for generating/using the admin-openrc isn't clear. 
As a reminder some part of the code is using this aswell :
https://github.com/BeyondTheClouds/enos/blob/master/enos/ansible/group_vars/all.yml#L14

**Comment by msimonin** [comment]
Even if it's still wip I've gone through https://github.com/rcherrueau/enos/commit/5314a2bad759251b6683e3f2a6d05695c87a7200

I like the way you are solving the issue !
