### ISSUE TITLE
write init-os using a dedicated ansible playbook

### ISSUE THREAD

**Issue by msimonin** [BeyondTheClouds/enos#117]
As we are moving many part of the code in ansible in our workflow (e.g  #116 ). I've the feeling we should use Ansible as well to do the `init-os` phase. And, who knows, write the openstack provider using ansible sounds not that absurd (see #83 ).

**Comment by rcherrueau** [comment]
Good idea. Do you think we should use ansible [openstack module](https://docs.ansible.com/ansible/list_of_cloud_modules.html#openstack)?

**Comment by msimonin** [comment]
yes, this is what I have in mind.
This module depends on shade, which in turns depends on some openstack client. I think it would be also wise to remove the openstack client dependency we have and only rely on shade.

**Comment by msimonin** [comment]
After discussion it came that the init phase should be customizable and be part of a scenario.
The fact to do that using ansible or whatever scripts could be let to the user.
