### ISSUE TITLE
Parameterize ceph monitors host

### ISSUE THREAD

**Issue by rcherrueau** [BeyondTheClouds/enos#119]
I perform my tests at Nantes since Rennes vlan are dead. To make deployment faster I wanna use Nantes' Ceph, but monitors host are fixed in [`roles/registry/file/ceph.conf`](https://github.com/BeyondTheClouds/enos/blob/6876c892f76617e46d5952a0a5ebbbf93080239c/enos/ansible/roles/registry/files/ceph.conf#L2). I rather propose to parameterize this into the `reservation.yml`.

**Comment by msimonin** [comment]
:+1 
But don't forget that you'll have to set up a pool, rbds, ... in nantes aswell.
