### ISSUE TITLE
pip install git+git://github.com/BeyondTheClouds/enos@master#egg=enos

### ISSUE THREAD

**Issue by msimonin** [BeyondTheClouds/enos#14]
Do we currently support this way of installing the tool ?
I may be wrong but I think that, by default, there will be an issue with the inventory directory as well as the rally directory.

**Comment by rcherrueau** [comment]
Use `env` to get the path of the `current`directory.

**Comment by rcherrueau** [comment]
I confirm that the software cannot find the `inventories` directory. But, I finally think that this is a normal behavior. You should fill the `reservation.yaml:inventory` variable with the correct path.

**Comment by msimonin** [comment]
> You should fill the reservation.yaml:inventory variable with the correct path.
absolute path ? 

Does it require the user to create its own inventory (or copy it) ? or point to the one provided in the package location ?
My point is that it's not very practical. When installing with pip I expect the tool to have decent default parameters to work out of the box.

**Comment by rcherrueau** [comment]
Let me check how things work at kolla side. I propose to follow a similar behavior.

**Comment by msimonin** [comment]
I would like to remove the pip installation as long as we haven't decided  how to handle local input directories (e.g inventories).
Nevertheless, shaker can launch scenario and some of them are shipped with the package. 
To refer to those who are shipped with the package shaker use an alias : 

```
  --scenario SCENARIO   Comma-separated list of scenarios to play. Each entity
                        can be a file name or one of aliases:
                        "misc/instance_metadata", "misc/static_agent",
                        "misc/static_agents_pair",
                        "openstack/cross_az/full_l2",
[...]
```

**Comment by rcherrueau** [comment]
I propose to comment the installation section in the README and keep this issue open until we fix the problem.

**Comment by msimonin** [comment]
After discussion we came to the point that we could have a `enos` package in pypi. 
The worklow would change a little : 
```
enos new  <my scenario> # This phase will create a scenario skeletton (inventory, init scripts, workload dir)
cd my-scenario
enos deploy # as usual
```
