### ISSUE TITLE
Integrate some code quality tools

### ISSUE THREAD

**Issue by msimonin** [BeyondTheClouds/enos#162]
e.g : 
codacy gives some hints to improve the code quality

other ? 
![image](https://user-images.githubusercontent.com/2486813/27744203-ea4e08b4-5dbe-11e7-9058-a4dd6a8203c8.png)

![image](https://user-images.githubusercontent.com/2486813/27744253-1214f3b2-5dbf-11e7-9a25-a7e1247e9064.png)

Therem also may be some feedbacks integrated when pull requests are made.

**Comment by rcherrueau** [comment]
Nice tool, I like the "Code Style" tab. Is it possible to give ownership to Didier?

**Comment by msimonin** [comment]
codacy is reporting some hints on each pr, let's live with it a little.
