### ISSUE TITLE
[vagrant] Could vagrant root be `resultdir` instead of  `current dir`?

### ISSUE THREAD

**Issue by rcherrueau** [BeyondTheClouds/enos#163]
See provider[ enos_vagrant.py:89](https://github.com/BeyondTheClouds/enos/blob/ac3c72c383fac9480fed22c8394f6662be4982d2/enos/provider/enos_vagrant.py#L89)

**Comment by msimonin** [comment]
yes, as long as we make sure to not create new virtual machines each time `enos up` is called.
Maybe we will need to set the `VAGRANT_CWD` environment variable behind the scene[1]

[1]: https://www.vagrantup.com/docs/other/environmental-variables.html#vagrant_cwd

**Comment by msimonin** [comment]
Will be addressed in #14
