### ISSUE TITLE
Can `up` be broken down into two subtasks?

### ISSUE THREAD

**Issue by ivotron** [BeyondTheClouds/enos#176]
The use case I have in mind is for users that want to bring up openstack without installing the local registries (i.e. stop before executing ansible)

**Comment by msimonin** [comment]
[inviting @rcherrueau :)]

For now the `up` phase is responsible to  : 
1. get the ressources (provider specific)
2. initialize them (install ansible dependencies, make some network configurations, install docker)
3. install a docker registry
4. optionnaly install a monitoring stack 
It seems possible to split into two subtasks (1,2 & 3,4) we just need to make sure that after 2. we have everything in the environment to run Kolla in the following phase.
Note that for your specific use case we have #142 that would address the use case of enabling/disabling the registry.

**Comment by rcherrueau** [comment]
Would it be OK if we make the installation of the registry optional?

**Comment by ivotron** [comment]
thanks @msimonin @rcherrueau . `--skip-install` that's what I went for in #180

**Comment by msimonin** [comment]
The registry installation is now optionnal (see #186 ).
This will be available for `pike`.

**Comment by msimonin** [comment]
@ivotron : I'm working on [enoslib](https://github.com/BeyondTheClouds/enoslib)
One of the goal is to keep the EnOS experience but to be able to apply it to anything (not only OpenStack). In this context you'll be able to write your own `up` phase.
As you can see, many things are missing (including a proper documentation) especially the chameleon provider. So if you have any expectation for this provider, let us know before I integrate it :)
