### ISSUE TITLE
Defines networks rather than interfaces

### ISSUE THREAD

**Issue by rcherrueau** [BeyondTheClouds/enos#197]
The actual implementation makes  the hypotheses that every machine have the same interface names. But that's not true! We should rather ask for networks in the reservation file and then let enos find which interface is link to what interface.

- `provider::init` returns a list of roles and networks. networks is a list of 2 network object:
  + network_net: pick vip inside this network.
  + neutron_external_net: rewrite `enos init` with this one.

**Comment by msimonin** [comment]
It's now addressed with the EnOSlib support (starting from 4.1.0)
