### ISSUE TITLE
Make enos supports more than 2 networks

### ISSUE THREAD

**Issue by rcherrueau** [BeyondTheClouds/enos#199]
Make enos supports all type of networks provided by kolla (see, https://github.com/openstack/kolla-ansible/blob/b1b501cc08108c944aa6686bfd5ff8a5f829195e/ansible/group_vars/all.yml#L114-L123)

- [ ] G5k/Vagrant/OpenStack: Go with an enhanced resource description where each node says networks it needs
- [ ] Static: Ask the user to provide the list of networks
- [ ] Write an automatic transformation between the simple version (at the top of the reservation file) and the enhanced one (under the provider key).

Note that the enhanced description does not make sens for Chameleon/Bare-metal.

**Comment by msimonin** [comment]
It's now possible with the EnOSlib support and the advanced configuration format.
