### ISSUE TITLE
[stable/pike] no network connectivity between netns

### ISSUE THREAD

**Issue by msimonin** [BeyondTheClouds/enos#204]
> Note that it is recommended to use Debian 9 (stretch) as base image for your deployment as you may experience some issue with the network connectivity of your VMs.
It has been chosen to keep Debian 8 (jessie) for `3.0.0` but you can still upgrade your base image to use the latest Debian. Please make sure to change your network interface name mapping in the reservation file accordingly to your environment.

Historical issue below :
Let's try to narrow down this issue

# Observation

When deploying stable/pike on g5k, there is no network connectivity between the various netns enforced by neutron.
For example we can't ping the gateway (`192.168.0.1` in the router namespace) from the dhcp server namespace (`192.168.0.2`).
This result in VMs not getting their dhcp leases.

# Tests : 

## work with

* `enos 2.3.0` (stable/ocata), docker images `beyondtheclouds:4.0.3`, provider `g5k`
* `enos stable/pike on ubuntu16.04`
* `enos stable/pike on debian9`

## doesn't work with

* `enos stable/pike` and docker images `beyondtheclouds:5.0.1`, provider `g5k`
* `enos stable/pike` and docker images `beyondtheclouds:5.0.1`, provider `vagrant` (`debian/contrib-jessie64`, `ovs`) [comment 1]
* `enos stable/pike` and docker images `beyondtheclouds:5.0.1`, provider `vagrant` (`debian/contrib-jessie64`, `linuxbridge`) [comment 2]

**Comment by rcherrueau** [comment]
Doesn't work with `beyondtheclouds:5.0.1` provider `Vagrant`

**Comment by rcherrueau** [comment]
Same problem with linux bridge (i.e., `neutron_plugin_agent: "linuxbridge"`).

**Comment by rcherrueau** [comment]
Tested with ubuntu 16.04 and it works.

**Comment by rcherrueau** [comment]
Tested with Debian 9.1 and it works.

**Comment by rcherrueau** [comment]
This may be a kernel issue. Kernel version is 4.9 on Debian 9.1 and 3.16 on Debian 8.

**Comment by rcherrueau** [comment]
It works on g5k with the following configuration : 
```yaml
provider:
  type: g5k
  env_name: stretch-x64-min
```
And on vagrant with the `bento/Debian-9.1`.

@msimonin May I ask you to upgrade [BeyondTheClouds/enoslib](https://github.com/BeyondTheClouds/enoslib) accordingly?

**Comment by msimonin** [comment]
I think enos provider could pass the right option to each enoslib provider (`env_name`|`box`|`image`)

**Comment by rcherrueau** [comment]
For g5k, `ifconfig` doesn't exist on `stretch-x64-min`, so we should change the [`ifconfig` bash command done on all nodes](https://github.com/BeyondTheClouds/enos/blob/18cd36fa45c34512ccb55351a01d3a7a854c6757/enos/provider/g5k.py#L312) with an `ip` bash command.

**Comment by msimonin** [comment]
ah !
https://github.com/BeyondTheClouds/enoslib/blob/master/enoslib/infra/enos_g5k/utils.py#L19

**Comment by msimonin** [comment]
done in https://github.com/BeyondTheClouds/enoslib/commit/0d6605f67eb7b27d0e8c2c18fb66d00850c52d14

**Comment by rcherrueau** [comment]
If you are OK, I will set `debian9-min-nfs` as the default env for g5k?

**Comment by denaitre** [comment]
You mean `debian9-x64-nfs`?

**Comment by rcherrueau** [comment]
Oh, yes you are right: `debian9-x64-nfs` or `debian9-x64-min`.

**Comment by msimonin** [comment]
👍 
Note that the interface naming may differ from debian8 and debian9. We should mitigate the effort for users by providing decent defaults in the reservation.yml (at least we should check if changes are required).
Note also that specifying the interface names is no longer required when using enoslib (it can autodetect the interface names)

**Comment by rcherrueau** [comment]
In `debian9-x64-...`, NIC names have been changed to follow debian8.

**Comment by rcherrueau** [comment]
Using `debian-x64-nfs` makes the deployment failed with the following error.

```
UNNING HANDLER [common : Initializing toolbox container using normal user] *******************************
fatal: [econome-6-kavlan-4.nantes.grid5000.fr]: FAILED! => {"changed": false, "cmd": ["docker", "exec", "-t", "kolla_toolbox", "/usr/bin/ansible", "--version"], "delta": "0:00:00.074857", "end": "2018-02-19 17:24:39.800552", "failed": true, "rc": 1, "start": "2018-02-19 17:24:39.725695", "stderr": "Error response from daemon: Container d7754cb94b5ad877fe2718ebc3008b4a7aaa767a9bc43f0887160f294cce8264 is restarting, wait until the container is running", "stderr_lines": ["Error response from daemon: Container d7754cb94b5ad877fe2718ebc3008b4a7aaa767a9bc43f0887160f294cce8264 is restarting, wait until the container is running"], "stdout": "", "stdout_lines": []}
```

Everything works well with `debian9-x64-min`.

**Comment by msimonin** [comment]
we need to stop the nscd service which is enabled on the `nfs` image.

https://bugs.launchpad.net/kolla-ansible/+bug/1680139

I sugeest to do it in the common part.

**Comment by rcherrueau** [comment]
Any preference for the Vagrant provider? [`debian/contrib-strecth64`](https://app.vagrantup.com/debian/boxes/contrib-stretch64) now seems to support vboxfs, but I never tried it. Otherwise, I tried [`bento/debian-9`](https://app.vagrantup.com/bento/boxes/debian-9) and it works well.

**Comment by msimonin** [comment]
+1 for bento
