### ISSUE TITLE
Add coveralls coverage report from Travis CI

### ISSUE THREAD

**Issue by amitkumarj441** [BeyondTheClouds/enos#209]
**What I did**
Adding coveralls integration to Travis CI so that we can get a coverage badge.

**How to verify it**
Travis CI will run and hopefully not fail, and then we can add a coverage badge

@msimonin someone with write access and an account on Travis CI may have to enable coveralls to get a badge.

**Comment by msimonin** [comment]
Is there any chance to get the coverage in codacy (I would prefer before extending to another third party tool) ?
You also should know that we are in the process of rewriting enos using https://github.com/BeyondTheClouds/enoslib
So maybe unit test and increasing the coverage should go there first.

**Comment by amitkumarj441** [comment]
@msimonin Yes, I guess `pip install codacy-coverage` will do it. We can do the same unit test and coverage in [enoslib](https://github.com/BeyondTheClouds/enoslib)
