### ISSUE TITLE
The content targeted by the debian image URL has moved

### ISSUE THREAD

**Issue by dpertin** [BeyondTheClouds/enos#228]
The following command: `curl -o /tmp/debian-9.qcow2 https://cdimage.debian.org/cdimage/openstack/current-9/debian-9-openstack-amd64.qcow2` gives the following output:

```<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://gensho.ftp.acc.umu.se/cdimage/openstack/current-9/debian-9-openstack-amd64.qcow2">here</a>.</p>
<hr>
<address>Apache/2.4.29 (Unix) Server at cdimage.debian.org Port 443</address>
</body></html>
```

As a consequence, any request to boot a VM based on the debian image leads to a frozen instance.

I propose to ask cURL to follow redirection.

**Comment by msimonin** [comment]
Closed by ee56d030484b16f786968ee4d19b90e394144dd3
