### ISSUE TITLE
Problems on installation

### ISSUE THREAD

**Issue by jad-darrous** [BeyondTheClouds/enos#25]
Actually, I have a problem on installation. When I run this command from a frantend  
`pip install git+git://github.com/BeyondTheClouds/enos@master#egg=enos`
I got this log at end

```
creating /usr/local/lib/python2.7/dist-packages/enos

error: could not create '/usr/local/lib/python2.7/dist-packages/enos': Permission denied

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-ojF8sT/enos/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-_lzaQi-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-ojF8sT/enos
Storing debug log for failure in /home/jaddarrous/.pip/pip.log
```

The message says that I do not have permission. Knowing that `sudo` can't be used on the frontend, I reserved an instance and I ran the command again with `sudo-g5k` and I got this error log:

```
import pytz as _pytz

ImportError: No module named pytz

error in setup command: Error parsing /tmp/pip-build-eyIa3H/positional/setup.cfg: ImportError: No module named pytz

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-eyIa3H/positional/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Pz__bH-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-eyIa3H/positional
Storing debug log for failure in /root/.pip/pip.log
```

Did I miss something?

**Comment by asimonet** [comment]
Hello, you are right about the Grid'5000 frontend and sudo. However, it seems much simpler to me to just run `pip install --user git+git://github.com/BeyondTheClouds/enos@master#egg=enos` on the frontend rather than reserving an instance.

**Comment by msimonin** [comment]
I may suggest you to switch to the installation from sources https://github.com/BeyondTheClouds/enos#contribute
as pip installation is broken (see #14). 

Thanks for reporting this, hopefully you can use pip soon.

**Comment by jad-darrous** [comment]
Thank you! It works :) I didn't know about the `--user` flag.

**Comment by jad-darrous** [comment]
It works with pip. I think it was my fault.

**Comment by msimonin** [comment]
Hello @jad-darrous, as a follow up the installation procedure has been changed (see the readme)
Let us know how things are going.

**Comment by jad-darrous** [comment]
Hello @msimonin , it works! no issue with the deployment.
