### ISSUE TITLE
[g5k] default image in doc is wrong

### ISSUE THREAD

**Issue by jrbalderrama** [BeyondTheClouds/enos#255]
At [default provider configuration](https://enos.readthedocs.io/en/stable/provider/grid5000.html#default-provider-configuration) page the proper `env_name` should be set to `debian9-x64-min`.

**Comment by msimonin** [comment]
We should not duplicate the defaults in the doc but link to the code directly

**Comment by jrbalderrama** [comment]
In that case the suggestion becomes an enhancement in a new ticket
