### ISSUE TITLE
[g5k] Site configured in generated networks is hardcoded 

### ISSUE THREAD

**Issue by jrbalderrama** [BeyondTheClouds/enos#272]
Target site is not properly set because it is hard coded: 

https://github.com/BeyondTheClouds/enos/blob/9c01dff45028f476356bce43fa488b93f899af2a/enos/provider/g5k.py#L29-L39

This issue will be address after BeyondTheClouds/enoslib#51 is solved

**Comment by msimonin** [comment]
Partially addressed in #276

**Comment by msimonin** [comment]
The fixes above is minimal but allow to deploy enos on any cluster of G5K.
Multisite isn't supported, but its support is postponed.
