### ISSUE TITLE
Add parametrize new task from cli

### ISSUE THREAD

**Issue by jrbalderrama** [BeyondTheClouds/enos#315]
Instead of generating a configuration file with all the possible configurations. Add an option (`-p` ?) to create a specific reservation file targeting a provider or all by default (current behaviour).
Alternatively add also an option to write results to a file (`-o` ?) natively without the need of piping the result of the command `enos new`

**Comment by msimonin** [comment]
yes we could have something: 

```
enos new -p g5k
```
and this can generate a **valid** configuration

**Comment by jrbalderrama** [comment]
This also involves to update the templates
