### ISSUE TITLE
Implement `enos build <provider> [--options]` to install once and use many times a base image

### ISSUE THREAD

**Issue by msimonin** [BeyondTheClouds/enos#325]
Rationale: 
1. I don't want the docker images to be pulled every single time I use Enos
2. The same for any dependency pulled from internet (apt, pip...) 

Note that, for 1.,  another solution would be to use a persistent registry or a registry backed by a rbd (ceph on g5k only). These solutions don't seem to be convenient for most users and difficult to setup in a dynamic environment such as G5K.

Action Items:
- [ ] add `enos build` in `cli.py`
- [ ] orchestrate the build in `tasks.py` inspired by https://gitlab.inria.fr/discovery/kenan/blob/1d0bc663ff0a41b9c41e08ea3facbaae1c2c2ac2/kenan/provider/static/task.py#L115-126
- [ ] add a `get_build_conf` in each enos provider so that the instruction on tasks.py build the complete conf and then call `deploy`.

**Comment by msimonin** [comment]
I merged this in EnOSlib : https://gitlab.inria.fr/discovery/enoslib/commit/c66bddbbab3d2316442e1e4a39c88d28048136e4

In short, I suggest to generate a `working_dir` on the frontend (e.g using the current directory) to ease the use of the build process.

**Comment by msimonin** [comment]
I also merged this: https://gitlab.inria.fr/discovery/enoslib/commit/b2ed4b3e33fd3c5cdbf9f3bf65a6c01616472238

So, I suggest to generate `strategy=copy` so that, for vmong5k, the disk image is directly reusable (without the qemu-img commit step).

**Comment by jrbalderrama** [comment]
We can also add a post build option to commit the results:
- `vagrant package ...` for vagrant
- `tgz-g5k ...` for g5k
- Stop the VM to reuse it safely for vmg5k
