### ISSUE TITLE
enos bench failed on task rally

### ISSUE THREAD

**Issue by sphilippot** [BeyondTheClouds/enos#338]
provider : grid5000
enos: 6.0.0
sites: all
clusters: all
task rally failed on Initialize database during enos bench
Creating database: sqlite:////home/rally/.rally/rally.db", "DB Migration Error: 'DB schema is already under version control. Use upgrade() instead'"

Last successful job on jenkins  g5k was  April 15, 2020

**Comment by msimonin** [comment]
Hi @sphilippot 

Thanks for this report.
Seems related to the fact that we're pointing to the latest docker image. I've pinned rally to the last working image (1.x.x). It seems that using 2.x.x would require some changes in the enos/bench code. I'd prefer to switch to 2.x.x for the next major version of EnOS.
