### ISSUE TITLE
A g5k deployment without compute nodes fails with " KeyError: 'compute' "

### ISSUE THREAD

**Issue by rcherrueau** [BeyondTheClouds/enos#34]
At line 169 of [provider/g5k.py](https://github.com/BeyondTheClouds/enos/blob/d223b0670f093a0f5375fb98aca0fb3964846b69/enos/provider/g5k.py#L169) the provider expects some compute nodes in order to bound them on the /tmp directory. 

The case there are no compute, the script fails.

**Comment by denaitre** [comment]
Related code:
* collectd: [ansible/roles/collectd/tasks/main.yml](https://github.com/BeyondTheClouds/enos/blob/master/enos/ansible/roles/collectd/tasks/main.yml#L22)
* cAdvisor: [ansible/roles/cadvisor/tasks/main.yml#L19](https://github.com/BeyondTheClouds/enos/blob/master/enos/ansible/roles/cadvisor/tasks/main.yml#L19) [ansible/roles/cadvisor/tasks/main.yml#L38](https://github.com/BeyondTheClouds/enos/blob/master/enos/ansible/roles/cadvisor/tasks/main.yml#L38)

**Comment by rcherrueau** [comment]
You can add `enable_monitoring: false` in your reservation.yaml as a workaround for collectd and cAdvisor problem. Of course, this will deactivate monitoring features.

**Comment by denaitre** [comment]
The group compute is mandatory for nova in kolla: [ansible/roles/nova/tasks/start_compute.yml#L27](https://github.com/openstack/kolla-ansible/blob/7bb88390d88aebfc257e09e7e055a09fe4121782/ansible/roles/nova/tasks/start_compute.yml#L27)

**Comment by msimonin** [comment]
Yep I guess it's the same story as storage and network.
In this cases the generated should contain an empty list of machine otherwise it's a bug of enos.

**Comment by msimonin** [comment]
Any progress here ?

**Comment by rcherrueau** [comment]
The bind to /tmp problem with g5k have been fix. Not sure for kolla part: is the `compute` group mandatory and has to contain nodes in case of `enable_nova`?

**Comment by msimonin** [comment]
I'm closing this. It seems not that bad after all :)
