### ISSUE TITLE
Memcached crashed with stable/ocata

### ISSUE THREAD

**Issue by rcherrueau** [BeyondTheClouds/enos#69]
Kolla-ansible failed to launch memcached with the following error:
```
Running command: '/usr/bin/memcached -vv -l 10.44.0.18 -p 11211 -c 5000'
failed to set rlimit for open files. Try starting as root or requesting smaller maxconns value.
```

The problem comes from the `-c 5000` that is too big.

**Comment by msimonin** [comment]
We should maybe increase the limit during the `up` phase.

**Comment by rcherrueau** [comment]
@msimonin can you be a little bit more verbose? From my point of you, there are two possibilities:
1. Remove the `-c` option with an enos patch
2. Do some test with a small value fixed with `{{ memcached_connection_limit }}`

**Comment by msimonin** [comment]
We should investigate  the use of the [`sysctl`](https://docs.ansible.com/ansible/sysctl_module.html) module of ansible to increase the max number of open files possible.
