### ISSUE TITLE
--force-kolla-deploy and --force-deploy

### ISSUE THREAD

**Issue by alebre** [BeyondTheClouds/enos#76]
Hi all, 

It would be great to have two additional options in kolla. 
--force-kolla-deploy: 
   This option should delete containers on the different nodes and invoke enos to redeploy the selected openstack like if it was the first time. This option is mandatory when you want to perform several trials of an experiment without redeploying everything (kadeploy + kolla)

--force-deploy: 
  This option should (re)deploy everything (kadeploy + kolla)

**Comment by msimonin** [comment]
👍

**Comment by rcherrueau** [comment]
The --force-deploy already exist. For the `--force-kolla-deploy` I rather propose a `enos os --force` which has the behavior you describe.

Once should notice that it's not necessary to remove all containers. We should keep all containers set up during the `up` phase.

**Comment by msimonin** [comment]
This should maybe leverage this :https://github.com/openstack/kolla-ansible/blob/master/tools/cleanup-containers
The question is : will it be faster than a `force-deploy` ?

**Comment by alebre** [comment]
please add something to --force (just to help the user to know what he/she is going to enforce)

**Comment by msimonin** [comment]
If we implement it I suggest also to add something to the `--force` option.

**Comment by rcherrueau** [comment]
Implemented in #148
