### ISSUE TITLE
[provider] Lets the user define the provider into the reservation file

### ISSUE THREAD

**Issue by rcherrueau** [BeyondTheClouds/enos#79]
In most cases, you write a reservation.yml for a specific provider. So adding the provider name into the reservation.yml will make stuff clearer.

**Comment by msimonin** [comment]
Does it implies we could remove the `--provider option` in the cli ?

**Comment by rcherrueau** [comment]
I guess. Even if there are no many differences between a description for G5k or vbox, the resource language sticks to a provider in the end. So removing the cli option seams a good idea.

**Comment by msimonin** [comment]
I would like to have this :)

**Comment by msimonin** [comment]
Can we schedule to do it in the same timeframe as the openstack/chameleon provider ?

**Comment by rcherrueau** [comment]
I can do that today. What do you prefer between (1) removing the `--provider` argument and make it mandatory into the reservation.yml, or (2) keep the `--provider` argument and mark it as deprecated (so we will remove it in the next release)?

**Comment by msimonin** [comment]
(2) would be nice, but honestly I think we can go for (1)

**Comment by msimonin** [comment]
Let's discuss :)
Having this would be nice because it would allow custom options to be passed to the provider.
```
provider:
  type: <name>
  options: <object>
```
