### ISSUE TITLE
vbox : VMs get a name that doesn't match their final role

### ISSUE THREAD

**Issue by matrohon** [BeyondTheClouds/enos#89]
If we set such a section in reservation.yaml : 

resources:
  medium:
   compute: 1
   network: 1
  large:
   control: 1

then, the following section is generated in the env file : 

rsc:
  compute:
  - !!python/object:execo.host.Host {address: network-0, keyfile: /home/mat/dev/enos/.vagrant/machines/network-0/libvirt/private_key,
    port: null, user: root}
  control:
  - !!python/object:execo.host.Host {address: control-0, keyfile: /home/mat/dev/enos/.vagrant/machines/control-0/libvirt/private_key,
    port: null, user: root}
  medium:
  - !!python/object:execo.host.Host {address: control-0, keyfile: /home/mat/dev/enos/.vagrant/machines/control-0/libvirt/private_key,
    port: null, user: root}
  - !!python/object:execo.host.Host {address: compute-0, keyfile: /home/mat/dev/enos/.vagrant/machines/compute-0/libvirt/private_key,
    port: null, user: root}
  - !!python/object:execo.host.Host {address: network-0, keyfile: /home/mat/dev/enos/.vagrant/machines/network-0/libvirt/private_key,
    port: null, user: root}
  network:
  - !!python/object:execo.host.Host {address: compute-0, keyfile: /home/mat/dev/enos/.vagrant/machines/compute-0/libvirt/private_key,
    port: null, user: root}

we can see the confusing situation where the VM named compute-0 has the role "network" and the VM named network-0 has the role "compute".

**Comment by msimonin** [comment]
What disturb me here is that you get more machines in your env than initially requested.
We are maybe in the situation where an previous uncleaned env is polluting the current. 

Does it happen also if you remove you env (removing the symlink : `current` should be enough) ?

**Comment by matrohon** [comment]
hi @msimonin, I get the exact same situation after removing the current link, and every previous enos_* environment.
